### PR TITLE
Add /fcr:tx to extendTransaction URI

### PR DESCRIPTION
**Pull request by whikloj**
Addresses https://github.com/Islandora-CLAW/chullo/issues/31

### CODE REVIEW

**Comment by DiegoPino** [comment]
@whikloj, looks pretty nice. Will test but just for sanity because i'm sure it's ok.

**Comment by DiegoPino** [comment]
@whikloj i'm ok with this. Will give other @Islandora-CLAW/7-x-2-x-committers the day to check. If no issues on this i will merge tomorrow AM.

**Comment by acoburn** [comment]
:+1:

**Comment by DiegoPino** [comment]
done! Love consensus

**Pull request merged**
