### PR TITLE
Test enhancement

### PR DESCRIPTION
**Pull request by peter279k**
# What does this Pull Request do?

Test enhancement.

# What's new?

It seems that these tests for `php-7.1+` versions in Travis CI build.

- It should require `php-7.1` version at least and upgrade the PHPUnit version to `7.x` version.
- Change PHPUnit namespace to class-based PHPUnit namespace.

### CODE REVIEW

**Comment by whikloj** [comment]
@peter279k thanks for your contribution. To accept this the Islandora Foundation needs an individual contributor license. You can find more information [here](https://github.com/Islandora/islandora/wiki/Contributor-License-Agreements).

If you are okay with it, please download the iCLA form, fill it out and (what I did was) snap a picture and send that to community at islandora dot ca

**Comment by peter279k** [comment]
Hi @whikloj, thank you for your reply.

I will do this contributor sign at my available time.

**Comment by peter279k** [comment]
Hi @whikloj, just notice that I've sent the individual contributor license agreement to the community team recently.

**Comment by manez** [comment]
CLA now on file! Thank you @peter279k

**Comment by whikloj** [comment]
Thanks @peter279k 👏

**Pull request merged**
