### PR TITLE
Updates for PHP 7.4 and Composer 2.

### PR DESCRIPTION
**Pull request by ruebot**
**GitHub Issue**:
  - https://github.com/Islandora/Crayfish/pull/110
  - https://github.com/Islandora-Devops/ansible-role-crayfish/pull/36

# What does this Pull Request do?

Updates for PHP 7.4 and Composer 2.

- Update to require PHP 7.4
- Update easyrdf to v1+
- Update php_codesniffer to v3+
- Update phpunit to v9+
- Update phpcpd to v6+
- Update tests to work with newer version of phpunit
- Update EasyRdf namespaces since they use proper namespaces with 1.0.0
- Update README

# How should this be tested?

- TravisCI should take care of it.

# Additional Notes:

I'm fairly certain I'll need this for: https://github.com/Islandora/Crayfish/pull/110

# Interested parties

@rosiel @seth-shaw-unlv @dannylamb

### CODE REVIEW

**Comment by dannylamb** [comment]
@ruebot Any chance we can cover 7.3 and 7.4 here? I'm hesitant to jump straight to 7.4 here if we don't have to.

**Comment by dannylamb** [comment]
Oh, I see now: https://travis-ci.org/github/Islandora-Devops/ansible-role-crayfish/jobs/748458293#L761

:hankey:, no choice then.

**Comment by dannylamb** [comment]
I updated the codecov settings to make `dev` the default branch.

**Comment by whikloj** [comment]
Just to second the question about PHP 7.3 support. I have been out of the loop but did we stop supporting it?

**Comment by elizoller** [comment]
@whikloj danny cited https://travis-ci.org/github/Islandora-Devops/ansible-role-crayfish/jobs/748458293#L761 above

**Comment by whikloj** [comment]
Thanks all (and hi Nick 👋 ), I guess this answers my question. 
By the time we get to Islandora 8 it'll be on PHP 8 anyways. Will have to look in the RHEL software collections library to see how far I can get before it stops.

**Comment by dannylamb** [comment]
FWIW ISLE is already on php 7.4, which is why i never noticed it when moving everything over to composer 2 for it

**Comment by dannylamb** [comment]
IMO we can just fix codecov later.  I'd rather move on, since this is blocking some sprint things.  Let's just be sure to advertise this change when releasing.  Sounds like the kinda thing that warrants a changelog entry.

**Comment by elizoller** [comment]
so what does this need? someone to pull it in, composer install, and make sure chullo still works?

**Review by elizoller — APPROVED** [review]
I can't speak to the code-cov piece but this is what I did to test:
i have a d9 box (built from that islandora-playbook PR #196), i went into `/var/www/html/drupal/vendora/islandora/chullo` and checked out pull/89 and then ran composer install in there and then i went to islandora and made an item and verified it made it to fedora.

**Pull request merged**
